export interface User {
  xp: number,
  name: string,
  lvl: number,
  str: number,
  agi: number,
  luck: number,
  int: number,
  will: number,
  wisdom: number,
  craft: number,
  legacy: number,
  diplomacy: number,
  charisma: number,
}